# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.0.0
maven_group = fish.spiknyckel
archives_base_name = beautful_mod

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.12.2
loader_version = 0.19.3

raven_build = 1
sparrow_build = 1
feather_build = 31

osl_version = 0.16.3
